name: CI/CD dev

on:
  push:
    branches: [develop]

jobs:
  run-ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  docker-build:
    name: Docker build
    uses: ./.github/workflows/docker-build.yml
    needs: run-ci

  infra-dev:
    name: Infra dev
    uses: ./.github/workflows/infra.yml
    needs: docker-build
    with:
      env: dev

  deploy-dev:
    name: Deploy dev
    uses: ./.github/workflows/deploy.yml
    needs: infra-dev
    with:
      env: dev
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

