name: Regression cron prod

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  schedule:
    # Every day at 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  regression-tests-prod-cron:
    name: Regression tests prod (cron)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Regression tests
        uses: ./.github/actions/run-tests/regression
